[package]
name = "just-watch"
version = "0.0.1"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
serde = {version = "1.0.145", features = ["derive"]}
reqwest ={version = "0.11.12", features = ["json"]}
rust-embed="6.4.1"